import React from 'react';
import { useTheme } from '../../contexts/ThemeContext';
import usePopup from '../../hooks/usePopup';
import BeautifulPopup from '../common/BeautifulPopup';
import { FiCopy } from 'react-icons/fi';
import { FaWhatsapp, FaTwitter, FaLinkedin, FaFacebook } from 'react-icons/fa';

const ShareModal = ({ attempt, onClose }) => {
  const { isDark } = useTheme();
  const { popupState, showSuccess, showError, hidePopup } = usePopup();

  const formatTime = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const getScoreMessage = (percentage) => {
    if (percentage >= 90) return { text: 'Outstanding Performance! 🌟' };
    if (percentage >= 80) return { text: 'Excellent Work! 🎉' };
    if (percentage >= 70) return { text: 'Good Performance! 👏' };
    if (percentage >= 60) return { text: 'Fair Performance 📈' };
    return { text: 'Keep Practicing! 💪' };
  };

  const shareToSocial = (platform) => {
    const scoreMessage = getScoreMessage(attempt.percentage);
    const shareText = `🎯 Just completed "${attempt.testTitle}" and scored ${attempt.percentage}%! ${scoreMessage.text} 

📊 Performance:
✅ ${attempt.score}/${attempt.totalQuestions} correct answers
⏱️ Completed in ${formatTime(attempt.timeSpent)}
🎓 Difficulty: ${attempt.difficulty}

#TestSeries #LearningProgress #QuizMaster`;

    const shareUrl = window.location.href;

    const urls = {
      whatsapp: `https://wa.me/?text=${encodeURIComponent(shareText + '\n\n' + shareUrl)}`,
      twitter: `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`,
      linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}&summary=${encodeURIComponent(shareText)}`,
      facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}&quote=${encodeURIComponent(shareText)}`
    };

    if (urls[platform]) {
      window.open(urls[platform], '_blank', 'width=600,height=400');
    }
  };

  const copyToClipboard = async () => {
    const scoreMessage = getScoreMessage(attempt.percentage);
    const shareText = `🎯 Test Results: "${attempt.testTitle}"

📊 Score: ${attempt.percentage}% (${attempt.score}/${attempt.totalQuestions} correct)
⏱️ Time: ${formatTime(attempt.timeSpent)}
🎓 Difficulty: ${attempt.difficulty}

${scoreMessage.text}

Generated by QuizMaster Test Series Platform`;

    try {
      await navigator.clipboard.writeText(shareText);
      showSuccess('Results copied to clipboard!', 'Copied Successfully');
      onClose();
    } catch (error) {
      console.error('Failed to copy:', error);
      showError('Failed to copy to clipboard', 'Copy Error');
    }
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className={`backdrop-blur-xl border rounded-3xl p-8 max-w-lg w-full shadow-2xl ${
        isDark 
          ? 'bg-gradient-to-br from-gray-800/95 to-gray-900/95 border-gray-600/40' 
          : 'bg-white/95 border-slate-200/60 shadow-slate-200/40'
      }`}>
        <div className="text-center mb-6">
          <h3 className={`text-2xl font-bold mb-2 ${
            isDark ? 'text-white' : 'text-slate-800'
          }`}>Share Your Results</h3>
          <p className={isDark ? 'text-gray-400' : 'text-slate-600'}>Let others know about your performance!</p>
        </div>

        {/* Social Media Buttons */}
        <div className="grid grid-cols-2 gap-4 mb-6">
          <button
            onClick={() => shareToSocial('whatsapp')}
            className={`flex items-center gap-3 p-4 border rounded-xl transition-all duration-300 hover:scale-105 ${
              isDark 
                ? 'bg-green-600/20 hover:bg-green-600/30 border-green-500/40 text-green-300' 
                : 'bg-green-100/60 hover:bg-green-200/60 border-green-400/60 text-green-700'
            }`}
          >
            <FaWhatsapp className="w-6 h-6" />
            <span>WhatsApp</span>
          </button>

          <button
            onClick={() => shareToSocial('twitter')}
            className={`flex items-center gap-3 p-4 border rounded-xl transition-all duration-300 hover:scale-105 ${
              isDark 
                ? 'bg-blue-600/20 hover:bg-blue-600/30 border-blue-500/40 text-blue-300' 
                : 'bg-blue-100/60 hover:bg-blue-200/60 border-blue-400/60 text-blue-700'
            }`}
          >
            <FaTwitter className="w-6 h-6" />
            <span>Twitter</span>
          </button>

          <button
            onClick={() => shareToSocial('linkedin')}
            className={`flex items-center gap-3 p-4 border rounded-xl transition-all duration-300 hover:scale-105 ${
              isDark 
                ? 'bg-blue-700/20 hover:bg-blue-700/30 border-blue-600/40 text-blue-300' 
                : 'bg-blue-200/60 hover:bg-blue-300/60 border-blue-500/60 text-blue-800'
            }`}
          >
            <FaLinkedin className="w-6 h-6" />
            <span>LinkedIn</span>
          </button>

          <button
            onClick={() => shareToSocial('facebook')}
            className={`flex items-center gap-3 p-4 border rounded-xl transition-all duration-300 hover:scale-105 ${
              isDark 
                ? 'bg-blue-800/20 hover:bg-blue-800/30 border-blue-700/40 text-blue-300' 
                : 'bg-indigo-100/60 hover:bg-indigo-200/60 border-indigo-400/60 text-indigo-700'
            }`}
          >
            <FaFacebook className="w-6 h-6" />
            <span>Facebook</span>
          </button>
        </div>

        {/* Copy to Clipboard */}
        <button
          onClick={copyToClipboard}
          className={`w-full flex items-center justify-center gap-3 p-4 border rounded-xl transition-all duration-300 hover:scale-105 mb-6 ${
            isDark 
              ? 'bg-purple-600/20 hover:bg-purple-600/30 border-purple-500/40 text-purple-300' 
              : 'bg-purple-100/60 hover:bg-purple-200/60 border-purple-400/60 text-purple-700'
          }`}
        >
          <FiCopy className="w-5 h-5" />
          <span>Copy Results to Clipboard</span>
        </button>

        {/* Close Button */}
        <button
          onClick={onClose}
          className={`w-full p-3 rounded-xl transition-colors ${
            isDark 
              ? 'bg-gray-700/50 hover:bg-gray-600/50 text-gray-300' 
              : 'bg-slate-100/60 hover:bg-slate-200/60 text-slate-700 hover:text-slate-800'
          }`}
        >
          Close
        </button>
      </div>

      {/* Beautiful Popup */}
      <BeautifulPopup
        {...popupState}
        onClose={hidePopup}
      />
    </div>
  );
};

export default ShareModal;
