import React from 'react';
import { FiCopy } from 'react-icons/fi';
import { FaWhatsapp, FaTwitter, FaLinkedin, FaFacebook } from 'react-icons/fa';

const ShareModal = ({ attempt, onClose }) => {
  const formatTime = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const getScoreMessage = (percentage) => {
    if (percentage >= 90) return { text: 'Outstanding Performance! 🌟' };
    if (percentage >= 80) return { text: 'Excellent Work! 🎉' };
    if (percentage >= 70) return { text: 'Good Performance! 👏' };
    if (percentage >= 60) return { text: 'Fair Performance 📈' };
    return { text: 'Keep Practicing! 💪' };
  };

  const shareToSocial = (platform) => {
    const scoreMessage = getScoreMessage(attempt.percentage);
    const shareText = `🎯 Just completed "${attempt.testTitle}" and scored ${attempt.percentage}%! ${scoreMessage.text} 

📊 Performance:
✅ ${attempt.score}/${attempt.totalQuestions} correct answers
⏱️ Completed in ${formatTime(attempt.timeSpent)}
🎓 Difficulty: ${attempt.difficulty}

#TestSeries #LearningProgress #QuizMaster`;

    const shareUrl = window.location.href;

    const urls = {
      whatsapp: `https://wa.me/?text=${encodeURIComponent(shareText + '\n\n' + shareUrl)}`,
      twitter: `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`,
      linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}&summary=${encodeURIComponent(shareText)}`,
      facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}&quote=${encodeURIComponent(shareText)}`
    };

    if (urls[platform]) {
      window.open(urls[platform], '_blank', 'width=600,height=400');
    }
  };

  const copyToClipboard = async () => {
    const scoreMessage = getScoreMessage(attempt.percentage);
    const shareText = `🎯 Test Results: "${attempt.testTitle}"

📊 Score: ${attempt.percentage}% (${attempt.score}/${attempt.totalQuestions} correct)
⏱️ Time: ${formatTime(attempt.timeSpent)}
🎓 Difficulty: ${attempt.difficulty}

${scoreMessage.text}

Generated by QuizMaster Test Series Platform`;

    try {
      await navigator.clipboard.writeText(shareText);
      alert('📋 Results copied to clipboard!');
      onClose();
    } catch (error) {
      console.error('Failed to copy:', error);
      alert('❌ Failed to copy to clipboard');
    }
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-gradient-to-br from-gray-800/95 to-gray-900/95 backdrop-blur-xl border border-gray-600/40 rounded-3xl p-8 max-w-lg w-full shadow-2xl">
        <div className="text-center mb-6">
          <h3 className="text-2xl font-bold text-white mb-2">Share Your Results</h3>
          <p className="text-gray-400">Let others know about your performance!</p>
        </div>

        {/* Social Media Buttons */}
        <div className="grid grid-cols-2 gap-4 mb-6">
          <button
            onClick={() => shareToSocial('whatsapp')}
            className="flex items-center gap-3 p-4 bg-green-600/20 hover:bg-green-600/30 border border-green-500/40 text-green-300 rounded-xl transition-all duration-300 hover:scale-105"
          >
            <FaWhatsapp className="w-6 h-6" />
            <span>WhatsApp</span>
          </button>

          <button
            onClick={() => shareToSocial('twitter')}
            className="flex items-center gap-3 p-4 bg-blue-600/20 hover:bg-blue-600/30 border border-blue-500/40 text-blue-300 rounded-xl transition-all duration-300 hover:scale-105"
          >
            <FaTwitter className="w-6 h-6" />
            <span>Twitter</span>
          </button>

          <button
            onClick={() => shareToSocial('linkedin')}
            className="flex items-center gap-3 p-4 bg-blue-700/20 hover:bg-blue-700/30 border border-blue-600/40 text-blue-300 rounded-xl transition-all duration-300 hover:scale-105"
          >
            <FaLinkedin className="w-6 h-6" />
            <span>LinkedIn</span>
          </button>

          <button
            onClick={() => shareToSocial('facebook')}
            className="flex items-center gap-3 p-4 bg-blue-800/20 hover:bg-blue-800/30 border border-blue-700/40 text-blue-300 rounded-xl transition-all duration-300 hover:scale-105"
          >
            <FaFacebook className="w-6 h-6" />
            <span>Facebook</span>
          </button>
        </div>

        {/* Copy to Clipboard */}
        <button
          onClick={copyToClipboard}
          className="w-full flex items-center justify-center gap-3 p-4 bg-purple-600/20 hover:bg-purple-600/30 border border-purple-500/40 text-purple-300 rounded-xl transition-all duration-300 hover:scale-105 mb-6"
        >
          <FiCopy className="w-5 h-5" />
          <span>Copy Results to Clipboard</span>
        </button>

        {/* Close Button */}
        <button
          onClick={onClose}
          className="w-full bg-gray-700/50 hover:bg-gray-600/50 text-gray-300 p-3 rounded-xl transition-colors"
        >
          Close
        </button>
      </div>
    </div>
  );
};

export default ShareModal;
