import React from 'react';
import { useTheme } from '../../contexts/ThemeContext';
import usePopup from '../../hooks/usePopup';
import BeautifulPopup from '../common/BeautifulPopup';
import { FiCopy } from 'react-icons/fi';
import { FaXTwitter } from 'react-icons/fa6'; 
import { FaWhatsapp, FaLinkedin, FaFacebook } from 'react-icons/fa';

const ShareModal = ({ attempt, onClose }) => {
  const { isDark } = useTheme();
  const { popupState, showSuccess, showError, hidePopup } = usePopup();

  // Helper function to format time in mm:ss format
  const formatTime = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  // Returns motivational message based on score percentage
  const getScoreMessage = (percentage) => {
    if (percentage >= 90) return { text: 'Outstanding Performance! 🌟' };
    if (percentage >= 80) return { text: 'Excellent Work! 🎉' };
    if (percentage >= 70) return { text: 'Good Performance! 👏' };
    if (percentage >= 60) return { text: 'Fair Performance 📈' };
    return { text: 'Keep Practicing! 💪' };
  };

  // Opens social media sharing dialog for selected platform
  const shareToSocial = (platform) => {
    const scoreMessage = getScoreMessage(attempt.percentage);
    const shareUrl = 'https://quiz-master-go.vercel.app/';
    const shareText = `🎯 Just completed "${attempt.testTitle}" and scored ${attempt.percentage}%! ${scoreMessage.text}

📊 Performance:
✅ ${attempt.score}/${attempt.totalQuestions} correct answers
⏱️ Completed in ${formatTime(attempt.timeSpent)}
🎓 Difficulty: ${attempt.difficulty}

#TestSeries #LearningProgress #QuizMaster

Try it -> ${shareUrl}`;

    const platformUrls = {
      whatsapp: `https://wa.me/?text=${encodeURIComponent(shareText)}`,
      twitter: `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`,
      linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}&summary=${encodeURIComponent(shareText)}`,
      facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}&quote=${encodeURIComponent(shareText)}`
    };

    if (platformUrls[platform]) {
      window.open(platformUrls[platform], '_blank', 'width=600,height=400');
    }
  };

  // Copies formatted results to clipboard with success feedback
  const copyToClipboard = async () => {
    const scoreMessage = getScoreMessage(attempt.percentage);
    const shareUrl = 'https://quiz-master-go.vercel.app/';
    const shareText = `🎯 Test Results: "${attempt.testTitle}"

📊 Score: ${attempt.percentage}% (${attempt.score}/${attempt.totalQuestions} correct)
⏱️ Time: ${formatTime(attempt.timeSpent)}
🎓 Difficulty: ${attempt.difficulty}

#TestSeries #LearningProgress #QuizMaster

${scoreMessage.text}

Try it -> ${shareUrl}

Generated by QuizMaster Test Series Platform`;

    try {
      await navigator.clipboard.writeText(shareText);
      showSuccess('Results copied to clipboard!', 'Copied Successfully');
      onClose();
    } catch (error) {
      console.error('Failed to copy:', error);
      showError('Failed to copy to clipboard', 'Copy Error');
    }
  };

  // Social media button configuration for cleaner code
  const socialButtons = [
    {
      platform: 'whatsapp',
      icon: FaWhatsapp,
      label: 'WhatsApp',
      colors: isDark 
        ? 'hover:bg-green-500/20 border-green-500/30 hover:border-green-400/50 text-green-300'
        : 'hover:bg-green-50 border-green-200 hover:border-green-300 text-green-700'
    },
    {
      platform: 'twitter',
      icon: FaXTwitter,
      label: 'X',
      colors: isDark 
        ? 'hover:bg-slate-500/20 border-slate-500/30 hover:border-slate-400/50 text-slate-300'
        : 'hover:bg-slate-50 border-slate-200 hover:border-slate-300 text-slate-700'
    },
    {
      platform: 'linkedin',
      icon: FaLinkedin,
      label: 'LinkedIn',
      colors: isDark 
        ? 'hover:bg-blue-500/20 border-blue-500/30 hover:border-blue-400/50 text-blue-300'
        : 'hover:bg-blue-50 border-blue-200 hover:border-blue-300 text-blue-700'
    },
    {
      platform: 'facebook',
      icon: FaFacebook,
      label: 'Facebook',
      colors: isDark 
        ? 'hover:bg-indigo-500/20 border-indigo-500/30 hover:border-indigo-400/50 text-indigo-300'
        : 'hover:bg-indigo-50 border-indigo-200 hover:border-indigo-300 text-indigo-700'
    }
  ];

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className={`backdrop-blur-xl border rounded-3xl p-6 max-w-md w-full shadow-2xl transform transition-all duration-300 ${
        isDark 
          ? 'bg-gray-800/90 border-gray-600/40 shadow-gray-900/50' 
          : 'bg-white/95 border-white/60 shadow-slate-200/40'
      }`}>
        
        {/* Header Section */}
        <div className="text-center mb-6">
          <h3 className={`text-xl font-bold mb-2 ${
            isDark ? 'text-white' : 'text-slate-800'
          }`}>
            Share Your Results
          </h3>
          <p className={`text-sm ${
            isDark ? 'text-gray-300' : 'text-slate-600'
          }`}>
            Let others know about your performance!
          </p>
        </div>

        {/* Social Media Buttons Grid */}
        <div className="grid grid-cols-2 gap-3 mb-6">
          {socialButtons.map(({ platform, icon: Icon, label, colors }) => (
            <button
              key={platform}
              onClick={() => shareToSocial(platform)}
              className={`flex items-center justify-center gap-2 p-3 border rounded-xl transition-all duration-200 hover:scale-[1.02] active:scale-95 cursor-pointer ${
                isDark 
                  ? `bg-gray-700/50 border-gray-600/40 text-gray-200 ${colors}`
                  : `bg-white border-gray-200 text-gray-700 ${colors}`
              }`}
              aria-label={`Share to ${label}`}
            >
              <Icon className="w-5 h-5" />
              <span className="text-sm font-medium">{label}</span>
            </button>
          ))}
        </div>

        {/* Copy to Clipboard Button */}
        <button
          onClick={copyToClipboard}
          className={`w-full flex items-center justify-center gap-2 p-3 border rounded-xl transition-all duration-200 hover:scale-[1.01] active:scale-95 mb-4 cursor-pointer ${
            isDark 
              ? 'bg-purple-600/20 border-purple-500/30 hover:bg-purple-500/30 hover:border-purple-400/50 text-purple-200'
              : 'bg-purple-50 border-purple-200 hover:bg-purple-100 hover:border-purple-300 text-purple-700'
          }`}
          aria-label="Copy results to clipboard"
        >
          <FiCopy className="w-4 h-4" />
          <span className="text-sm font-medium">Copy Results</span>
        </button>

        {/* Close Button */}
        <button
          onClick={onClose}
          className={`w-full p-3 rounded-xl transition-all duration-200 hover:scale-[1.01] active:scale-95 text-sm font-medium cursor-pointer ${
            isDark 
              ? 'bg-gray-700/50 hover:bg-gray-600/60 text-gray-300 border border-gray-600/40 hover:border-gray-500/50'
              : 'bg-gray-100 hover:bg-gray-200 text-gray-700 border border-gray-200 hover:border-gray-300'
          }`}
          aria-label="Close modal"
        >
          Close
        </button>
      </div>

      {/* Success/Error Popup */}
      <BeautifulPopup
        {...popupState}
        onClose={hidePopup}
      />
    </div>
  );
};

export default ShareModal;
